name: Daily Commit

on:
  schedule:
    - cron: "30 4 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "nabin2004"
          git config user.email "olinabin2004@gmail.com"

      - name: Create a new file
        run: echo "This is an automated commit." >> automated-commit.txt

      - name: Commit changes
        run: |
          git add automated-commit.txt
          git commit -m "Automated daily commit"
          git push
